---
- name: Install Unity desktop environment
  apt: pkg=ubuntu-desktop state=present
  when: ansible_distribution == 'Ubuntu'

- name: Install Gnome desktop environment
  yum: name="@^gnome-desktop-environment" state=present
  when: ansible_distribution == 'rhel fedora'
